apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: edugrowth-ingress
  namespace: edugrowth
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - edugrowth.tn
        - www.edugrowth.tn
        - app.edugrowth.tn
      secretName: edugrowth-tls
  rules:
    - host: edugrowth.tn
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: website
                port:
                  number: 80
    - host: www.edugrowth.tn
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: website
                port:
                  number: 80
    - host: app.edugrowth.tn
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: crm-api
                port:
                  number: 4000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: crm-frontend
                port:
                  number: 80
