apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: crm-api-policy
  namespace: edugrowth
spec:
  podSelector:
    matchLabels:
      app: crm-api
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: crm-frontend
  egress:
    - to:
        - podSelector:
            matchLabels:
              app: mongo
      ports:
        - protocol: TCP
          port: 27017
