server {
  listen 80;
  server_name edugrowth.tn www.edugrowth.tn;

  location = /app {
    return 301 https://app.edugrowth.tn$request_uri;
  }

  location ^~ /app/ {
    return 301 https://app.edugrowth.tn$request_uri;
  }
}
